// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClbhl_Y8MQLWKxHMKqev8-GlgPDsoIq3M',
    appId: '1:1097958378845:web:4ac4e7e080dc266dd82cb4',
    messagingSenderId: '1097958378845',
    projectId: 'courantinfo-458d0',
    authDomain: 'courantinfo-458d0.firebaseapp.com',
    storageBucket: 'courantinfo-458d0.firebasestorage.app',
    measurementId: 'G-81EPBRKVPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9sIIN6Zuc3kzv5tCf3B9FYnGzTbg-J2U',
    appId: '1:1097958378845:android:03560814d9041dd3d82cb4',
    messagingSenderId: '1097958378845',
    projectId: 'courantinfo-458d0',
    storageBucket: 'courantinfo-458d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUzhIk-qig81DAozIPJrm3HzfEtTvl_tk',
    appId: '1:1097958378845:ios:0c9c4f52d8cd717fd82cb4',
    messagingSenderId: '1097958378845',
    projectId: 'courantinfo-458d0',
    storageBucket: 'courantinfo-458d0.firebasestorage.app',
    iosBundleId: 'com.example.courantCiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUzhIk-qig81DAozIPJrm3HzfEtTvl_tk',
    appId: '1:1097958378845:ios:0c9c4f52d8cd717fd82cb4',
    messagingSenderId: '1097958378845',
    projectId: 'courantinfo-458d0',
    storageBucket: 'courantinfo-458d0.firebasestorage.app',
    iosBundleId: 'com.example.courantCiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClbhl_Y8MQLWKxHMKqev8-GlgPDsoIq3M',
    appId: '1:1097958378845:web:d83c53e5cbd726dbd82cb4',
    messagingSenderId: '1097958378845',
    projectId: 'courantinfo-458d0',
    authDomain: 'courantinfo-458d0.firebaseapp.com',
    storageBucket: 'courantinfo-458d0.firebasestorage.app',
    measurementId: 'G-02DLSQDVFK',
  );
}
